### ISSUE TITLE
Add `requirements.txt` file

### ISSUE THREAD

**Issue by Jakob37** [linem/mjewel-plotting-tool#3]
A common practice in Python projects is to produce a `requirements.txt` file so that other (or yourself) can install exactly the same versions used to run the code.

Typically I would make a virtual environment and use it as such:

```
$ python -m virtualenv ~/venv/mjewel
$ source ~/venv/mjewel/bin/activate
(mjewel) $ pip install -r requirements.txt
```

You can generate the file simply by:

```
pip freeze > requirements.txt
```

This will only work if you are using a virtual environment though. Otherwise you'll spit out all the dependencies you have available on your laptop.

**Comment by Jakob37** [comment]
I wonder if this applies to packages though 🤔 Something we can look into

**Comment by linem** [comment]
The requirements for the package is now defined in the `pyproject.toml` file.

**Comment by Jakob37** [comment]
Nice! Let's close the issue then.
